import type {
  User,
  Stat,
  QuickAction,
  Event,
  Document,
  Announcement,
  Message,
  ChatChannel,
} from "./index";
import {
  Bell,
  Calendar,
  FileText,
  MessageCircle,
  Users,
  Eye,
} from "lucide-react";

export const defaultUser: User = {
  id: 1,
  name: "John Doe",
  role: "Manager",
  department: "Sales",
  avatar: "/api/placeholder/40/40",
};

export const stats: Stat[] = [
  {
    title: "Documents",
    value: "248",
    change: "+12%",
    icon: FileText,
    color: "text-blue-600",
  },
  {
    title: "Officer",
    value: "156",
    change: "+3%",
    icon: Users,
    color: "text-green-600",
  },
  {
    title: "Views",
    value: "12",
    change: "+2",
    icon: Eye,
    color: "text-orange-600",
  },
  {
    title: "Schedule",
    value: "8",
    change: "+2",
    icon: Calendar,
    color: "text-purple-600",
  },
];

export const quickActions: QuickAction[] = [
  {
    title: "Upload Document",
    description: "Share files with your team",
    icon: FileText,
    action: () => (window.location.href = "/documents"),
  },
  {
    title: "New Announcement",
    description: "Post company updates",
    icon: Bell,
    action: () => (window.location.href = "/announcements"),
  },
  {
    title: "Schedule Meeting",
    description: "Book conference rooms",
    icon: Calendar,
    action: () => (window.location.href = "/calendar"),
  },
  {
    title: "Start Chat",
    description: "Connect with colleagues",
    icon: MessageCircle,
    action: () => (window.location.href = "/chat"),
  },
];

export const recentActivities = [
  {
    action: "Document uploaded",
    file: "Q4_Report.pdf",
    time: "2 hours ago",
  },
  {
    action: "Meeting scheduled",
    file: "Team Standup",
    time: "4 hours ago",
  },
  {
    action: "Announcement posted",
    file: "Holiday Schedule",
    time: "1 day ago",
  },
  {
    action: "Document shared",
    file: "Budget_2024.xlsx",
    time: "2 days ago",
  },
];

export const latestAnnouncements = [
  {
    title: "System Maintenance",
    content: "Scheduled maintenance on Sunday 2 AM - 4 AM",
    priority: "high",
    time: "1 hour ago",
  },
  {
    title: "New Office Hours",
    content: "Updated working hours effective next Monday",
    priority: "medium",
    time: "3 hours ago",
  },
  {
    title: "Team Building Event",
    content: "Annual company retreat registration open",
    priority: "low",
    time: "1 day ago",
  },
];

export const defaultDocuments: Document[] = [
  {
    id: 1,
    name: "Q4_Financial_Report.pdf",
    type: "pdf",
    size: "2.4 MB",
    uploadedBy: "John Smith",
    uploadDate: "2024-03-08",
    accessLevel: "Manager",
    department: "Finance",
    downloads: 45,
    views: 120,
    shared: true,
  },
  {
    id: 2,
    name: "Marketing_Strategy_2024.docx",
    type: "document",
    size: "1.8 MB",
    uploadedBy: "Sarah Johnson",
    uploadDate: "2024-03-07",
    accessLevel: "Employee",
    department: "Marketing",
    downloads: 23,
    views: 67,
    shared: false,
  },
  {
    id: 3,
    name: "Budget_Analysis.xlsx",
    type: "spreadsheet",
    size: "845 KB",
    uploadedBy: "Mike Wilson",
    uploadDate: "2024-03-06",
    accessLevel: "Admin",
    department: "Finance",
    downloads: 12,
    views: 34,
    shared: true,
  },
  {
    id: 4,
    name: "Team_Photo_2024.jpg",
    type: "image",
    size: "3.2 MB",
    uploadedBy: "HR Department",
    uploadDate: "2024-03-05",
    accessLevel: "Guest",
    department: "HR",
    downloads: 89,
    views: 203,
    shared: true,
  },
];

export const defaultChannels: ChatChannel[] = [
  {
    id: "general",
    name: "General",
    type: "public",
    members: 156,
    unread: 0,
    requiredRole: "Guest",
  },
  {
    id: "announcements",
    name: "Announcements",
    type: "public",
    members: 156,
    unread: 3,
    requiredRole: "Guest",
  },
  {
    id: "it-support",
    name: "IT Support",
    type: "public",
    members: 45,
    unread: 1,
    requiredRole: "Employee",
  },
  {
    id: "management",
    name: "Management",
    type: "private",
    members: 12,
    unread: 0,
    requiredRole: "Manager",
  },
  {
    id: "admin",
    name: "Admin Only",
    type: "private",
    members: 3,
    unread: 0,
    requiredRole: "Admin",
  },
  {
    id: "sales-team",
    name: "Sales Team",
    type: "department",
    members: 25,
    unread: 2,
    requiredRole: "Employee",
    department: "Sales",
  },
  {
    id: "marketing-team",
    name: "Marketing Team",
    type: "department",
    members: 18,
    unread: 0,
    requiredRole: "Employee",
    department: "Marketing",
  },
];

export const defaultMessages: Record<string, Message[]> = {
  general: [
    {
      id: 1,
      user: "Sarah Johnson",
      role: "Manager",
      message: "Good morning everyone! Hope you all have a productive day.",
      timestamp: "09:15 AM",
      avatar: "/api/placeholder/32/32",
    },
    {
      id: 2,
      user: "Mike Wilson",
      role: "Employee",
      message: "Thanks Sarah! Looking forward to the team meeting later.",
      timestamp: "09:18 AM",
      avatar: "/api/placeholder/32/32",
    },
    {
      id: 3,
      user: "IT Department",
      role: "Admin",
      message: "Reminder: System maintenance tonight from 11 PM to 1 AM.",
      timestamp: "10:30 AM",
      avatar: "/api/placeholder/32/32",
      isSystem: true,
    },
  ],
  announcements: [
    {
      id: 1,
      user: "HR Department",
      role: "Admin",
      message: "New employee orientation scheduled for next Monday at 9 AM.",
      timestamp: "08:00 AM",
      avatar: "/api/placeholder/32/32",
      isSystem: true,
    },
  ],
  "it-support": [
    {
      id: 1,
      user: "John Doe",
      role: "Employee",
      message: "Having issues with the VPN connection. Can someone help?",
      timestamp: "02:30 PM",
      avatar: "/api/placeholder/32/32",
    },
  ],
};

export const defaultAnnouncements: Announcement[] = [
  {
    id: 1,
    title: "System Maintenance Scheduled",
    content:
      "We will be performing system maintenance on Sunday, March 10th from 2:00 AM to 4:00 AM. During this time, the system will be unavailable.",
    author: "IT Department",
    department: "IT",
    priority: "high",
    pinned: true,
    date: "2024-03-08",
    views: 145,
    likes: 12,
    comments: 3,
    tags: ["maintenance", "system"],
  },
  {
    id: 2,
    title: "New Employee Welcome",
    content:
      "Please join us in welcoming Sarah Johnson to the Marketing team. She will be starting as a Marketing Specialist on Monday.",
    author: "HR Department",
    department: "HR",
    priority: "medium",
    pinned: false,
    date: "2024-03-07",
    views: 89,
    likes: 25,
    comments: 8,
    tags: ["welcome", "team"],
  },
  {
    id: 3,
    title: "Q1 Company Meeting",
    content:
      "The quarterly company meeting is scheduled for March 15th at 10:00 AM in the main conference room. Attendance is mandatory for all employees.",
    author: "Management",
    department: "Management",
    priority: "high",
    pinned: true,
    date: "2024-03-06",
    views: 203,
    likes: 18,
    comments: 5,
    tags: ["meeting", "quarterly"],
  },
  {
    id: 4,
    title: "Office Lunch Event",
    content:
      "Join us for a catered lunch event next Friday at 12:00 PM. Please RSVP by Wednesday to help us plan accordingly.",
    author: "Social Committee",
    department: "General",
    priority: "low",
    pinned: false,
    date: "2024-03-05",
    views: 156,
    likes: 45,
    comments: 12,
    tags: ["social", "lunch"],
  },
];

export const defaultEvents: Event[] = [
  {
    id: 1,
    title: "Team Standup",
    description: "Daily team synchronization meeting",
    date: "2024-03-08",
    startTime: "09:00",
    endTime: "09:30",
    location: "Conference Room A",
    type: "meeting",
    organizer: "Sarah Johnson",
    attendees: ["John Doe", "Mike Wilson", "Sarah Johnson"],
    department: "Sales",
    isPrivate: false,
    color: "blue",
  },
  {
    id: 2,
    title: "Q1 Budget Review",
    description: "Quarterly budget analysis and planning session",
    date: "2024-03-08",
    startTime: "14:00",
    endTime: "16:00",
    location: "Boardroom",
    type: "presentation",
    organizer: "Management",
    attendees: ["Managers", "Finance Team"],
    department: "Finance",
    isPrivate: true,
    color: "red",
  },
  {
    id: 3,
    title: "System Maintenance",
    description: "Scheduled server maintenance and updates",
    date: "2024-03-10",
    startTime: "02:00",
    endTime: "04:00",
    location: "Server Room",
    type: "maintenance",
    organizer: "IT Department",
    attendees: ["IT Team"],
    department: "IT",
    isPrivate: false,
    color: "orange",
  },
  {
    id: 4,
    title: "Company All-Hands",
    description: "Monthly company-wide meeting",
    date: "2024-03-15",
    startTime: "10:00",
    endTime: "11:30",
    location: "Main Hall",
    type: "presentation",
    organizer: "CEO",
    attendees: ["All Employees"],
    department: "General",
    isPrivate: false,
    color: "green",
  },
];
